[package]
name = "die4Utils"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "2.1"
clap = { version = "4", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"
